name = "backend"
compatibility_date = "2024-07-25"
 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmI4MGIzYjktODczOS00MTFjLThjMzAtNjNhZWNkMzU1NzdlIiwidGVuYW50X2lkIjoiM2EyNmY2OWFhNDQ0YTQ1M2QwOGQ4NjA4NzQ4NDgwMGE0NDEyYTk0NDkzZDdiNGIzYWYwMjE0ZWJkOGM4OTFjNiIsImludGVybmFsX3NlY3JldCI6ImQwZTkxZjFhLTMzZDEtNGJlNS1hYWYxLWZlMzE4OGE2NzMyMSJ9.WtjsA79Y1OWX0EOz73YLzIXuDVyS1ZwHwCyHOIAjLLU"
SECRET="ZAZA"
